Feature/issue 123 credential management api
org-45/yantra-lite pull request #16
Opened 2023-10-11 10:09 UTC by rashilakhadka

### Description
This is a sample project that utilizes Credentials Management API.

### Changes Made
- Added username(rashilakhadka) as a list on the bootcamp.html file which contains the project link
- Added a folder participants folder named rashilakhadka(username) as suggested which contains the project

### Related Issues

### Checklist

- [x] I have tested these changes locally.
- [x] I have added/updated documentation as needed.
- [x] I have reviewed my code for potential issues.
- [x] I have followed the project's coding guidelines.
- [x] I have updated relevant comments and commit messages.

### Screenshots (if applicable)
![image](https://github.com/org-45/yantra-lite/assets/146622874/64044352-ff1f-4d0d-9018-bb2c7ee6a95a)
![image](https://github.com/org-45/yantra-lite/assets/146622874/c995496e-af3c-4b44-88b1-61335e51a40b)
![image](https://github.com/org-45/yantra-lite/assets/146622874/9f923694-4d87-4264-a105-914408a9cf94)
![image](https://github.com/org-45/yantra-lite/assets/146622874/3741c9d5-cb05-47c8-b2c8-c95424a3df3d)

### Additional Information

### Reviewer Request
@ankman007 

### By submitting this PR, I confirm that

- [x] I have read and understood the project's contributing guidelines.
- [x] This PR is ready for review and merging.
- [x] I understand that automated tests should pass before merging.

2023-10-11 16:40 UTC, manjilkoirala requested changes
The code seems good. Please link your issue to the PR description.

2023-10-11 17:11 UTC, ankman007 commented
@rashilakhadka Change "issue 123" to the issue you are solving.

2023-10-12 10:18 UTC, rashilakhadka commented
> The code seems good. Please link your issue to the PR description.

Done.

2023-10-12 10:18 UTC, rashilakhadka commented
> @rashilakhadka Change "issue 123" to the issue you are solving.

Done

2023-10-12 11:48 UTC, pfieffer approved these changes
LGTM
AAmazing work @rashilakhadka

2023-10-12 11:48 UTC, pfieffer commented on participants/rashilakhadka/script.js
> +    }
The early exit in case if the credential support is not available is a very good practice. 🚀

2023-10-12 12:56 UTC, manjilkoirala approved these changes

2023-10-12 12:57 UTC, manjilkoirala commented
Resolve the conflict then merge.
Thank you for the PR @rashilakhadka ☺️

2023-10-13 09:18 UTC, merged